### ISSUE TITLE
can not use with Pyinstaller

### ISSUE THREAD

**Issue by shingohu** [xxtea/xxtea-python#10]

**Comment by andot** [comment]
why not?

**Comment by shingohu** [comment]
you can try ,just import this library,and package by pyinstaller or pyexe
you will get 
```
Traceback (most recent call last):
  File "t.py", line 2, in <module>
    import xcffib
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "xcffib/__init__.py", line 24, in <module>
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "/usr/local/lib/python3.4/dist-packages/PyInstaller/loader/pyimod03_importers.py", line 389, in load_module
    exec(bytecode, module.__dict__)
  File "xcffib/ffi.py", line 256, in <module>
  File "cffi/api.py", line 373, in verify
  File "cffi/verifier.py", line 96, in load_library
  File "cffi/verifier.py", line 192, in _compile_module
  File "cffi/ffiplatform.py", line 38, in compile
  File "cffi/ffiplatform.py", line 62, in _build
  File "distutils/dist.py", line 973, in run_command
  File "distutils/cmd.py", line 107, in ensure_finalized
  File "distutils/command/build_ext.py", line 137, in finalize_options
  File "distutils/cmd.py", line 286, in set_undefined_options
  File "distutils/dist.py", line 846, in get_command_obj
  File "distutils/dist.py", line 832, in get_command_class
distutils.errors.DistutilsModuleError: invalid command 'build'
Failed to execute script t
```

**Comment by andot** [comment]
从上面的输出来看，这个问题来自于 cffi 这个库，你应该去这个库中反馈一下问题。
