### ISSUE TITLE
relpath exception

### ISSUE THREAD

**Issue by 36hours** [xxtea/xxtea-python#4]
hi, I use it on window7, and found the exception: 
```
E:\>python
Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import xxtea
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python27\lib\site-packages\xxtea\__init__.py", line 7, in <module>
    __SOURCES = [relpath(join(__PATH, 'xxtea.c'))]
  File "C:\Python27\lib\ntpath.py", line 529, in relpath
    % (path_prefix, start_prefix))
ValueError: path is on drive C:, start on drive E:
```
when the source path and the current directory  are on different drive path, the **relpath** throw exception.  It seems simple to fix this bug, like below
```
try:
    __SOURCES = [relpath(join(__PATH, 'xxtea.c'))]
except ValueError:
    __SOURCES = [join(__PATH, 'xxtea.c')]
```
Or remove the **relpath** function directly?

**Comment by andot** [comment]
OK, I removed relpath.
