### ISSUE TITLE
无法正常运行3.6

### ISSUE THREAD

**Issue by fingpop** [xxtea/xxtea-python#9]
Traceback (most recent call last):
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/cffi/cparser.py", line 5, in <module>
    from . import _pycparser as pycparser
ImportError: cannot import name '_pycparser'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Volumes/Study/Python/Web/base64.py", line 1, in <module>
    import xxtea
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/xxtea/__init__.py", line 9, in <module>
    ffi = FFI()
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/cffi/api.py", line 65, in __init__
    from . import cparser
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/cffi/cparser.py", line 7, in <module>
    import pycparser
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/pycparser/__init__.py", line 15, in <module>
    from .c_parser import CParser
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/pycparser/c_parser.py", line 11, in <module>
    from .ply import yacc
  File "/Volumes/Study/Python/Web/venv/lib/python3.6/site-packages/pycparser/ply/yacc.py", line 67, in <module>
    import base64
  File "/Volumes/Study/Python/Web/base64.py", line 6, in <module>
    encrypt_data = xxtea.encrypt(text,key)
AttributeError: module 'xxtea' has no attribute 'encrypt'

Console里面import xxtea也报错

**Comment by andot** [comment]
似乎是你的 cffi 包有问题，这个跟 xxtea 这个包没有直接关系。
